dist: xenial
sudo: required
group: beta
language: node_js
# Build fails if cache is enabled unless caches are manually cleared from travis settings
# cache:
#   directories:
#     - node_modules
matrix:
  fast_finish: true
install:
  - bash <(curl https://get.parity.io -L) -r v2.4.7
before_script:
  - export PATH=/snap/bin:${PATH}
  - npm install
script:
  - npm run test:ci
# safelist
# branches:
#   only:
#   - master
